### ISSUE TITLE
Feature request: List - bulletless variant

### ISSUE THREAD

**Issue by andoulla** [Atom-Learning/components#131]
## Component Name(\*) or Feature Name

List

## Description(\*)

We also need a variant that doesn't show any bullets before the list items. 

## Designs and UX wireframes(\*)

Please attach the designs and UX wireframes for this component (or links to the designs).

**Comment by hollg** [comment]
We also have some designs that include lists with icons used in place of bullet points. I wonder whether we could allow for that with the same work?

I'm not sure what the API would look like. In the example I'm thinking of, some items in the list have a green check icon and some have a grey X icon. Maybe something like this?

```tsx
<List bullet="circle">
  <List.Item bullet={CheckIcon} css={{ color: '$success500' }} >Item 1</List.Item>
  <List.Item bullet={CheckIcon} css={{ color: '$tonal500' }} >Item 2</List.Item>
</List>
```

The `bullet` prop on `List` and `List.Item` could allow specific strings (e.g. `"circle"`, `"none"`) for standard bullet styles or an SVG for our icons? And a `bullet` prop applied to a `List.Item` could override the one applied to a `List`.

@andoulla @thomasdigby what do you think?

**Comment by andoulla** [comment]
> We also have some designs that include lists with icons used in place of bullet points. I wonder whether we could allow for that with the same work?
> 
> I'm not sure what the API would look like. In the example I'm thinking of, some items in the list have a green check icon and some have a grey X icon. Maybe something like this?
> 
> ```tsx
> <List bullet="circle">
>   <List.Item bullet={CheckIcon} css={{ color: '$success500' }} >Item 1</List.Item>
>   <List.Item bullet={CrossIcon} css={{ color: '$tonal500' }} >Item 2</List.Item>
> </List>
> ```
> 
> The `bullet` prop on `List` and `List.Item` could allow specific strings (e.g. `"circle"`, `"none"`) for standard bullet styles or an SVG for our icons? And a `bullet` prop applied to a `List.Item` could override the one applied to a `List`.
> 
> @andoulla @thomasdigby what do you think?

Makes sense to combine the work for sure. I would assume that "none" would mean that there is not bullet at all. For standard bullet styles we could just omit the bullet prop instead. so if it isn't passed then we don't override the default behaviour

**Comment by hollg** [comment]
Yeah, I just wasn't sure what makes sense as the default behaviour. Though even if we default to no bullet, I think it would make sense to have the value of that prop default to "none" so that it can be set dynamically and shows up in dev tools.

**Comment by thomasdigby** [comment]
My initial thoughts on the custom icon are that it could (should?) be handled in user land. Feels like it's a bit too far away from our concept of generic UI elements, it's a specific implementation for a fairly specific use case.

The reset list and icon component would well work together for this

**Comment by andoulla** [comment]
So the user could set the List to not show any bullets and then compose the behaviour by combining the icon with the list item:
 ```
 <List bullet="none"><List.Item> <Icon/> <Text/></List.Item><List>
``` 


Just checking I'm on the same page

**Comment by thomasdigby** [comment]
Yeah, although more like

```jsx 
<List reset> // or <List.Reset> / <ListReset>
  <List.Item>
    <Icon is={Check} /> Here is the text
  </List.Item>
  <List.Item>
    <Icon is={Check} /> Here another item
  </List.Item>
<List>
```

**Comment by andoulla** [comment]
Ok that makes sense

**Comment by thomasdigby** [comment]
I'd say, if it can be achieved fairly easily by the user with components that already exist, then that's the convention we want to go for. Happy to hear opinions to the contrary though

**Comment by hollg** [comment]
That looks good to me!
