### ISSUE TITLE
Feature Request: Toggle, Toggle Field

### ISSUE THREAD

**Issue by mel-liow** [Atom-Learning/components#133]
## Component Name(\*) or Feature Name
Toggle, Toggle Field

## Description(\*)

- User can click between two states
- Toggle should be left when it's in the "off" state and right when it's "on"
- Use Toggle from Radix: https://radix-ui.com/primitives/docs/components/toggle 

## Designs and UX wireframes(\*)

Please attach the designs and UX wireframes for this component (or links to the designs).
<img width="223" alt="Screenshot 2021-04-20 at 16 49 42" src="https://user-images.githubusercontent.com/40150248/115426446-6990f100-a1f8-11eb-8044-7772e332b185.png">

**Comment by andoulla** [comment]
@mel-liow is this now released? @thomasdigby shall we close this issue?

**Comment by thomasdigby** [comment]
Yep its released, will close!
