### ISSUE TITLE
Feature request: RadioGroupField layout options

### ISSUE THREAD

**Issue by mel-liow** [Atom-Learning/components#143]
## Component Name(\*) or Feature Name
RadioGroupField

## Description(\*)

- Ability to format and pass styles to the `RadioGroup` to enable it to display horizontally

## Designs and UX wireframes(\*)

<img width="364" alt="Screenshot 2021-05-06 at 11 43 41" src="https://user-images.githubusercontent.com/40150248/117285793-502aae80-ae60-11eb-8c9f-a98a4098e93f.png">

## Additional Information
We should have rules or guidelines in place for the use case of each layout before introducing this. This would help with making sure that everything is properly documented and that we don’t start introducing inconsistencies across other components that may need optional layout formatting.

**Comment by thomasdigby** [comment]
Issue fixed in #177
