### ISSUE TITLE
Feature request: Optional label for Form Fields

### ISSUE THREAD

**Issue by Mhoog** [Atom-Learning/components#150]
## Component Name(\*) or Feature Name
All Form Fields (`InputField`, `CheckboxField` etc.)

## Description(\*)
The Form Field components are a nice and easy way to create different form fields without the hassle of hooking it up to `react-hook-form`. I noticed that the main reason why I sometimes cannot use the wrappers is because I don't need a label, for example when you combine different fields in one fieldset (dates, etc.).

It would be nice if the label is optional or can be hidden (not sure what is better accessibility-wise).

## Additional Information
Technically you could hide the label with a CSS selector like `& > label`, but I don't think that makes our code very clear to read.

**Comment by thomasdigby** [comment]
@Mhoog This was always the aim, provide something useful that bake in good conventions with required labels etc., but then also provide the underlying components that come together to create that "field" component so they can be composed together to create something unique. If we're finding that we're having to skip the "field" components more than we expected then I think it's worth making a change.

Could we require _some_ form of label? Either `label` or `aria-label`? Or do you require a custom label that you want to style differently?
