### ISSUE TITLE
Feature request: `FormData`

### ISSUE THREAD

**Issue by thomasdigby** [Atom-Learning/components#158]
## Component Name(\*) or Feature Name

`HiddenInput`, `FormData` or something similar

## Description(\*)

Something similar to this component, to take collect hidden data in a form:

```jsx
import React from 'react'

export const Hidden = React.forwardRef(({ fields }, ref) =>
  Object.keys(fields).map((key) => (
    <input ref={ref} key={key} type="hidden" name={key} value={fields[key] || ''} />
  ))
)
```

**Comment by hollg** [comment]
What's the use case for this component? My understanding was that this pattern is used when your submit button immediately fires a `POST` request, but our `Form` doesn't do that — we can do anything we like with our collected data inside the `onSubmit` function, including adding other data to it.

**Comment by thomasdigby** [comment]
@hollg You're absolutely right, I was trying to replicate a utility that's now redundant 👍
