### ISSUE TITLE
Feature request: Table

### ISSUE THREAD

**Issue by shaneakins** [Atom-Learning/components#166]
## Component Name(\*) or Feature Name

Table

## Description(\*)

The component should render a table with a optional header and footer

## Designs and UX wireframes(\*)

Please attach the designs and UX wireframes for this component (or links to the designs).

**Comment by thomasdigby** [comment]
Hey @shaneakins, do you have any more details on what you need for this component? The feature requests are super useful if they contain information about the scope of work, an idea of the implementation and some general designs or wireframes that help communicate your intent.

Also, I just want to clarify that this is a way for us to track requests for updates to the component lib, and not a literal request for Mariandi, Gary or I to build it. I'm sure that was made clear by Mariandi before but just wanted to double check! 😅

**Comment by shaneakins** [comment]
Hey @thomasdigby. Actually, I’m going to take a crack at building this as an exercise  to get my feet wet. Mariandi suggested I open the feature request as a first step. I know the details are lacking but I’ll be sure to fill it in once I have a better idea of what I should write.

**Comment by andoulla** [comment]
Closing as this was implemented
