### ISSUE TITLE
`CheckboxField` & `RadioGroupField` don't validate correctly

### ISSUE THREAD

**Issue by thomasdigby** [Atom-Learning/components#184]
## Expected Behaviour (\*)

`CheckboxField` and `RadioGroupField` should show a validation error if the props are passed correctly and the form is trigged

## Actual Behaviour (\*)
They do not show an error

## Steps to reproduce (\*)

Using `react-hook-form`s, `trigger`, it should show the error for both required fields

```tsx
const TriggerValidation = ({ trigger }) => {
  React.useEffect(() => {
    trigger()
  }, [trigger])
  return null
}

<Form
  onSubmit={() => null}
  render={(props) => (
    <>
      <TriggerValidation {...props} />
      <CheckboxField
        label="This is a checkbox"
        name="checkbox-error"
        validation={{ required: "This is the validation error" }}
      />
      <RadioGroupField
        name="options-error"
        label="Legend for radio fields"
        validation={{ required: "This is the validation error" }}
      >
        <RadioGroupField.Item label="This is a radio button" value="1" />
        <RadioGroupField.Item label="This is another radio button" value="2" />
      </RadioGroupField>
    </>
  )}
/>
```

**Comment by thomasdigby** [comment]
@Jdrazong Can you confirm that your fix also takes care of this issue?

**Comment by andoulla** [comment]
don't we need to pass required as a prop to field type components ?

**Comment by Jdrazong** [comment]
@andoulla @thomasdigby I updated the pull request im working on to handle required for Radio Inputs just now. Still need to change a few things to make validation work with dynamic forms since the errors are currently accessed by reflection and it won't work for dynamic fields without some changes

**Comment by Jdrazong** [comment]
@thomasdigby I dont think you can run validation just watching the trigger in use effect => just tried with:
`<Form
  onSubmit={() => null}
  render={(props) => (
    <>

      <CheckboxField
        label="This is a checkbox"
        name="checkbox-error"
        validation={{ required: "This is the validation error" }}
      />
      <RadioGroupField
        name="options-error"
        label="Legend for radio fields"
        validation={{ required: "This is the validation error" }}
      >
        <RadioGroupField.Item label="This is a radio button" value="1" />
        <RadioGroupField.Item label="This is another radio button" value="2" />
      </RadioGroupField>
      <button onClick={async () => await props.trigger()}>validate</button>
    </>
  )}
/>`

and it works properly

**Comment by thomasdigby** [comment]
> @thomasdigby I dont think you can run validation just watching the trigger in use effect => just tried with:
> 
> `<Form
> 
>   onSubmit={() => null}
> 
>   render={(props) => (
> 
>     <>
> 
> 
> 
>       <CheckboxField
> 
>         label="This is a checkbox"
> 
>         name="checkbox-error"
> 
>         validation={{ required: "This is the validation error" }}
> 
>       />
> 
>       <RadioGroupField
> 
>         name="options-error"
> 
>         label="Legend for radio fields"
> 
>         validation={{ required: "This is the validation error" }}
> 
>       >
> 
>         <RadioGroupField.Item label="This is a radio button" value="1" />
> 
>         <RadioGroupField.Item label="This is another radio button" value="2" />
> 
>       </RadioGroupField>
> 
>       <button onClick={async () => await props.trigger()}>validate</button>
> 
>     </>
> 
>   )}
> 
> />`
> 
> 
> 
> and it works properly

Thanks for this @Jdrazong, I realised this earlier and have updated the instance in our docs where we use this. Both are working well from your branch!
