### ISSUE TITLE
ValidationError: Icon and spacing from text shrink as text wraps to multiple lines

### ISSUE THREAD

**Issue by shaneakins** [Atom-Learning/components#192]
## Component Name (\*)
ValidationError

## Expected Behaviour (\*)
Regardless of the number of lines of text:
-  the icon should remain the same size
-  the icon should remain aligned to the top of the text block
-  the spacing from the text block should not change

## Actual Behaviour (\*)
When text wraps to more than one line, the icon and spacing shrink, and the icon vertically aligns with the middle of the text block

<img width="362" alt="Screen Shot 2021-07-28 at 13 00 20" src="https://user-images.githubusercontent.com/10671944/127315033-1ef62b2d-32bd-462f-8d15-a262d6ff160f.png">

## Steps to reproduce (\*)
Use enough text to wrap to multiple lines

## Other information (\*)

Google Chrome -  version 92.0.4515.107 (Official Build) (x86_64)
macOS Big Sur - version 11.4 (20F71)

**Comment by thomasdigby** [comment]
Fixed with #b25e400c0b381b6bccbdca9b0a23fadeb5a59272
