### ISSUE TITLE
Update request: Table

### ISSUE THREAD

**Issue by andoulla** [Atom-Learning/components#193]
## Component Name(\*) or Feature Name

Table

## Description(\*)

Update the styling of the table to match the agreed colours etc
Update the table to have 2 variants that alter the row height:
- one variant will have taller rows to allow using ActionIcons and buttons within it without compromising accessibility on mobile devices
- one variant will be slimmer for the instances where we are only displaying data

## Designs and UX wireframes(\*)

![image](https://user-images.githubusercontent.com/5703687/127327213-9c07a7ee-07d7-41a6-af1a-52c11545ccfa.png)

**Comment by thomasdigby** [comment]
@andoulla Do you think this should be a `size` prop on the table cell?

**Comment by andoulla** [comment]
> @andoulla Do you think this should be a `size` prop on the table cell?

sorry for missing this. In the review we used size as a prop just for future reference
