### ISSUE TITLE
RadioField: Using 'required' prop gives TS error; no red asterisk on 'required' label; gray line below label

### ISSUE THREAD

**Issue by shaneakins** [Atom-Learning/components#197]
## Expected Behaviour 

- Using 'required' prop will not generate a TS error
- Label should have a red asterisk when 'required' prop is used
- No line under label

## Actual Behaviour (\*)

- Using 'required' prop will not generate a TS error #2322
- Label does not  have a red asterisk when 'required' prop is used
- Gray line under label

## Other information 
![Screen Shot 2021-08-03 at 11 47 45](https://user-images.githubusercontent.com/10671944/127996392-3e482c2f-6fbd-45cd-926b-ccaf58f83a47.png)
![Screen Shot 2021-08-03 at 11 48 07](https://user-images.githubusercontent.com/10671944/127996409-27166dc4-c956-43b8-8a38-bb9c4d388aa3.png)
<img width="147" alt="Screen Shot 2021-08-03 at 11 57 18" src="https://user-images.githubusercontent.com/10671944/127997084-ada11917-5973-43d1-8e7e-82506417f4f5.png">

Please include Browser Name and version, OS and version

**Comment by thomasdigby** [comment]
@Jdrazong This might be relevant to your other issue
