### ISSUE TITLE
Table: problem

### ISSUE THREAD

**Issue by thomasdigby** [Atom-Learning/components#201]
`Table` should set `css={{ borderCollapse: 'collapse' }}` by default

**Comment by andoulla** [comment]
👍 we just need to make sure that can still overwrite it in the parent if we ever need to

**Comment by andoulla** [comment]
> > 👍 we just need to make sure that can still overwrite it in the parent if we ever need to
> 
> Yep just need to default it, I think it might even be necessary for our new table styles but I assume we're not seeing the issue due to global reset in our core app

but it would have shown up in the sandbox as we don't have a global reset there, do we?

**Comment by thomasdigby** [comment]
@andoulla We _do_ have a reset, but I'm not totally sure about the contents of it. Let me take a look and check that it's not being added there.

**Comment by thomasdigby** [comment]
Fixed with #c491484
