### ISSUE TITLE
Feature request: Tokenise Durations (ms)

### ISSUE THREAD

**Issue by avirati** [Atom-Learning/components#235]
## Feature Name

Duration (ms) Tokenisation

## Description

In favour of the fact that the values we use to style our components are tokenised, can we have all `durations` to be tokenised as well ?
example : `transition: 'transform $<token>'`

**Comment by MiguelGDLR** [comment]
@andoulla I have created a ticked for this in our backlog. [https://atomlearningltd.atlassian.net/browse/DS-89]
We can remove it from Github
