### ISSUE TITLE
Feature request: tabs

### ISSUE THREAD

**Issue by andoulla** [Atom-Learning/components#243]
## Component Name
Tabs

## Description(\*)

The following changes have been requested by the design team

- text: large body bold
- active: primary blue 
- Innactive:  grey tonnal 400
- select line: stroke 2 

## Designs and UX wireframes(\*)

![image](https://user-images.githubusercontent.com/5703687/139695251-8dbfbf0d-9775-49ad-9662-8faf709a4551.png)

https://www.figma.com/file/lXBJN5xPUgN6oUTcfSP01j/Atom-Assessments?node-id=3358%3A21805

**Comment by thomasdigby** [comment]
@andoulla How will the disabled state look alongside the inactive state here? I imagine it'll look pretty similar

**Comment by thomasdigby** [comment]
Have put an initial prototype together here https://github.com/Atom-Learning/components/pull/246

**Comment by andoulla** [comment]
> @andoulla How will the disabled state look alongside the inactive state here? I imagine it'll look pretty similar

I don't know, it seems that we are stripping away all the disabled states. I will ask jessica and come back to this ticket
