### ISSUE TITLE
Feature request: Search Input

### ISSUE THREAD

**Issue by andoulla** [Atom-Learning/components#244]
## Component Name

 Search Input

## Description(\*)

- Change the alignment from left to right
- Change icon colour

## Designs and UX wireframes(\*)

![image](https://user-images.githubusercontent.com/5703687/139695654-d9019ae2-1f67-4c94-bfe1-65f3c416a58a.png)

https://www.figma.com/file/lXBJN5xPUgN6oUTcfSP01j/Atom-Assessments?node-id=3358%3A21805

**Comment by andoulla** [comment]
@thomasdigby Do you think we should consider making the alignment a prop so people have more flexibility?

Or should we remain strict to enforce consistency

**Comment by thomasdigby** [comment]
@andoulla I think we should enforce some consistency here, my only issue with aligning to the right is that users may assume that it's a clickable button, "click here to search" sort of thing. We have that with the password visibility icon and the upcoming date input as well, that was the initial reason for aligning to the left.
