### ISSUE TITLE
Feature request: Avatar

### ISSUE THREAD

**Issue by thomasdigby** [Atom-Learning/components#303]
## Avatar

Please include the component name that you are amending or the suggested name if it is a new component/feature

## Description(\*)

https://www.radix-ui.com/docs/primitives/components/avatar - Radix might be overkill for local avatar images, but it has a nice DX

**Comment by andoulla** [comment]
I think Radix is a bit loaded but if we are going to replace all the different implementations we have it might be worth it. Anything we don't use can be tree-shaked anyway

**Comment by MiguelGDLR** [comment]
Can you close this issue, I've already added this component to our backlog with new design proposal
