### ISSUE TITLE
[Select]: Component doesn't accommodate a controlled usage

### ISSUE THREAD

**Issue by andoulla** [Atom-Learning/components#306]
## Component Name (\*)
Select

## Actual Behaviour (\*)
We have many situations where we need to use the `select` component in a controlled state (ie in EnhancedTable etc). Currently, it works but we get a console log error warning us to select one of the modes. 
```
 Select elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled select element and remove one of these props. More info: https://fb.me/react-controlled-components
    in select (created by Styled.select)
    in Styled.select (created by Select)
    in Select (at PaperSelection.tsx:136)
    in div (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in RunningLayerCountProvider (created by o)
    in o (created by ForwardRef)
    in RunningLayerCountProvider (created by o)
    in o (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in TotalLayerCountProvider (created by o)
    in o (created by ForwardRef)
    in TotalLayerCountProvider (created by o)
```

This is caused because `defaultValue` is set in the component. 
<img width="836" alt="image" src="https://user-images.githubusercontent.com/5703687/155694621-9d0d9f18-df08-49e2-857a-cabb8baedda2.png">

We could alter the component to request either the value or the default value and one of them to be mandatory instead of setting it in the component

## Steps to reproduce (\*)

Open any view that uses the select component in a controlled state (like PaperSelection or EnhancedTable with Pagination)

**Comment by thomasdigby** [comment]
Yep totally agree with this, we need to fix it
