### ISSUE TITLE
Can't override gridTemplateColumns in Grid component

### ISSUE THREAD

**Issue by chris-atomlearning** [Atom-Learning/components#309]
Was it intentional to force the gridTemplateColumns property on the Grid component? 
I had a case where I wanted to use  `gridTemplateColumns: '3fr 1fr 1fr' `.
Should it be before `...(css as any)`?
https://github.com/Atom-Learning/components/blob/8417a3248ca07f6a4d9d314eda626cdd55800e92/src/components/grid/Grid.tsx#L46

**Comment by kerryambt** [comment]
@Mhoog addressed this the other day so this is fixed. closing :)
